# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
ENV['SWIFT_VERSION'] = '5'
target 'PolyNetSample-tvOS-ObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!  
  pod 'PolyNetSDKtvOS', '~> 4'  
end


