# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
ENV['SWIFT_VERSION'] = '5'
target 'PolyNetSampleObjectiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!  
  pod 'PolyNetSDK', '4.35.1141'  
end


