# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
ENV['SWIFT_VERSION'] = '5'
target 'PolyNetSampleSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!  
  pod 'PolyNetSDK', '~> 4'  
end


